name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Trigger GitLab CI
      uses: masterleinad/gitlab-mirror-and-ci-action@master
      with:
        args: "https://code.ornl.gov/ecpcitest/alexa/"
      env:
        GITLAB_HOSTNAME: "code.ornl.gov"
        GITLAB_USERNAME: ${{ secrets.GITLAB_USER }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "6927"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
